spring.application.name=vehicleapi

spring.datasource.url=jdbc:postgresql://localhost:5432/vehicledb
spring.datasource.username=postgres
spring.datasource.password=nappy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true